openapi: '3.0.2'
info:
  description: 'dou api'
  version: 1.0.0
  title: 'dou api'
tags:
  - name: paintings
    description: Everything about your paintings
paths:
  /paintings:
    $ref: ./paths/paintings/index.yaml
components:
  schemas:
    Painting:
      $ref: ./components/schemas/Painting.yaml