version: 0.2

phases:
  pre_build:
    commands:
      - BASE_PATH=$(pwd)
  build:
    commands: 
      - |
        docker run --rm \
        -v ${BASE_PATH}/front:/app \
        -w /app node:10.15.3-alpine sh -c "yarn && yarn build"
  post_build:
    commands:
      - aws s3 sync ./build s3://{BUCKET_NAME}
      