version: 0.2

env:
  variables:
    DOCKER_REPOSITORY: abchyw8611/dou-api
    JAR_FILE: "build/libs/api-0.0.1-SNAPSHOT.jar"
  parameter-store:
    DOCKER_LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword
phases:
  install:
    runtime-versions:
      java: openjdk8
      docker: 18
    commands:
  pre_build:
    commands:
      - docker login -u abchyw8611 -p ${DOCKER_LOGIN_PASSWORD}
      - npm install -g yarn
      - yarn && yarn merge
      - sh api-schema/gen_source.sh class
  build:
    commands:
      - ./gradlew :api:build
      - cd api
      - docker build --no-cache -t ${DOCKER_REPOSITORY}:latest . --build-arg JAR_FILE=${JAR_FILE}
      - docker push ${REPOSITORY_URI}:latest
